### ISSUE TITLE
provide vscode remote containers example

### ISSUE THREAD

**Issue by apple-corps** [sbt/docker-sbt#186]
When trying to utilize container from vscode remote conatiners, get

```
[190 ms] Setting up container for folder or workspace: /project/path
[191 ms] Start: Check Docker is running
[191 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[389 ms] Server API version: 1.41
[406 ms] Start: Run: git rev-parse --show-cdup
[420 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/project/path --filter label=vsch.quality=stable
[625 ms] Start: Run: docker inspect --type container 8f2d080260d6
[830 ms] Start: Starting container
[831 ms] Start: Run: docker start 8f2d080260d6990d1afa6e5fc65c7315ec66a640779f4853f3f6fd4340a9d00b
[1378 ms] Command failed: docker start 8f2d080260d6990d1afa6e5fc65c7315ec66a640779f4853f3f6fd4340a9d00b
```

But works for other containers in vscode. Here's the configuration I tried by modifying another setup.

```devcontainer.json
{
    "name": "Scala Dev",
    "context": "..",
    "dockerFile": "Dockerfile",
    "settings": { 
        "terminal.integrated.shell.linux": "/bin/bash"
     },
      "extensions": [
      ],


    "mounts": [ "source=${localWorkspaceFolder},target=/work,type=bind" ],
    //"remoteUser": "sbtuser",
    "overrideCommand": false
}
```

```DOCKERFILE
FROM hseeberger/scala-sbt:8u222_1.3.5_2.13.1
#ENTRYPOINT ["/usr/bin/java"]
USER sbtuser
CMD ["sleep","30000"]
```

**Comment by apple-corps** [comment]
I was able to fork the java container example in vscode and install sbt fairly well. So that's an alternative option.

**Comment by apple-corps** [comment]
https://github.com/apple-corps/vscode-scala-remote-containers

**Comment by francisdb** [comment]
I'm not sure I get what the problem is as I am not using vscode

**Comment by Carbrex** [comment]
> When trying to utilize container from vscode remote conatiners, get
> 
> ```
> [190 ms] Setting up container for folder or workspace: /project/path
> [191 ms] Start: Check Docker is running
> [191 ms] Start: Run: docker version --format {{.Server.APIVersion}}
> [389 ms] Server API version: 1.41
> [406 ms] Start: Run: git rev-parse --show-cdup
> [420 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/project/path --filter label=vsch.quality=stable
> [625 ms] Start: Run: docker inspect --type container 8f2d080260d6
> [830 ms] Start: Starting container
> [831 ms] Start: Run: docker start 8f2d080260d6990d1afa6e5fc65c7315ec66a640779f4853f3f6fd4340a9d00b
> [1378 ms] Command failed: docker start 8f2d080260d6990d1afa6e5fc65c7315ec66a640779f4853f3f6fd4340a9d00b
> ```
> 
> But works for other containers in vscode. Here's the configuration I tried by modifying another setup.
> 
> ```json
> {
>     "name": "Scala Dev",
>     "context": "..",
>     "dockerFile": "Dockerfile",
>     "settings": { 
>         "terminal.integrated.shell.linux": "/bin/bash"
>      },
>       "extensions": [
>       ],
> 
> 
>     "mounts": [ "source=${localWorkspaceFolder},target=/work,type=bind" ],
>     //"remoteUser": "sbtuser",
>     "overrideCommand": false
> }
> ```
> 
> ```dockerfile
> FROM hseeberger/scala-sbt:8u222_1.3.5_2.13.1
> #ENTRYPOINT ["/usr/bin/java"]
> USER sbtuser
> CMD ["sleep","30000"]
> ```

If your dockerfile is at the root of the project like this
```
.
├── .devcontainer
│   └── devcontainer.json
└── Dockerfile
```
You would need to add .. in front of dockerfile

This worked for me
`.devcontainer/devcontainer.json`
```
{
  "name": "Scala Dev",
  "context": "..",
  "dockerFile": "../Dockerfile",
  "settings": {
    "terminal.integrated.shell.linux": "/bin/bash"
  },
  "extensions": [],
  "mounts": ["source=${localWorkspaceFolder},target=/work,type=bind"],
  "overrideCommand": false
}
```
`Dockerfile`
```
FROM hseeberger/scala-sbt:8u222_1.3.5_2.13.1
USER sbtuser
CMD ["sleep","30000"]
```

I think this issue can be closed now.

**Comment by francisdb** [comment]
Thanks @Carbrex
