### ISSUE TITLE
Docker push is broken

### ISSUE THREAD

**Issue by francisdb** [sbt/docker-sbt#194]
Hi Heiko, mind having a look at this?

https://github.com/hseeberger/scala-sbt/runs/6037187433?check_suite_focus=true

Maybe you changed your password?

**Comment by francisdb** [comment]
@hseeberger ping

**Comment by hseeberger** [comment]
Hi, sorry for the late reply. I do no longer actively follow Scala stuff.
Why not push the Docker images somewhere else?
Maybe forking this repo and then I can EOL it?

**Comment by francisdb** [comment]
see https://github.com/sbt/sbt/issues/6904

**Comment by francisdb** [comment]
@hseeberger was anything transferred on the docker hub side? I guess we can't just switch there as everything is under `hseeberger/scala-sbt`?

**Comment by eed3si9n** [comment]
Same name as GitHub - https://hub.docker.com/u/eed3si9n

**Comment by francisdb** [comment]
@eed3si9n can I get access to secrets on the repo so that I can add my secret for pushing to docker hub?

**Comment by eed3si9n** [comment]
@francisdb I just escalated https://github.com/orgs/sbt/teams/docker-sbt team to Admin on this repo. Hopefully that should give you the rights.

**Comment by francisdb** [comment]
thanks, I can add secrets now

**Comment by francisdb** [comment]
and we are live at https://hub.docker.com/repository/docker/sbtscala/scala-sbt/tags

**Comment by francisdb** [comment]
@hseeberger I wonder if there would be some way to point users to the new coordinates?
