### ISSUE TITLE
Switch to eclipse-temurin by default?

### ISSUE THREAD

**Issue by francisdb** [sbt/docker-sbt#200]
These come with ubuntu/alpine/windowsservercore

This is mentioned on the openjdk docker page

---

https://hub.docker.com/_/openjdk?tab=description

WARNING

If you are a user/consumer of Java, this image is probably not what you expect!

These images contain "vanilla" builds of the OpenJDK project provided by [Oracle](https://jdk.java.net/) or [the relevant "updates project lead"](https://github.com/docker-library/openjdk/issues/320#issuecomment-494050246) (depending on the version).

For a more "supported" experience, we recommend one of the following other Official Images (listed in alphabetical order with no intentional or implied preference):

    [amazoncorretto](https://hub.docker.com/_/amazoncorretto)
    [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin)
    [ibm-semeru-runtimes](https://hub.docker.com/_/ibm-semeru-runtimes)
    [ibmjava](https://hub.docker.com/_/ibmjava)
    [sapmachine](https://hub.docker.com/_/sapmachine)

**Comment by eed3si9n** [comment]
+1 on Eclipse Temurin. I explicitly endorse that on https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html page as well over distro JDKs.

**Comment by francisdb** [comment]
The question is a bit what is "by default"
We probably can't just switch as the images without qualifier are based on debian and temurin is based on ubuntu?
Maybe it's enough to:

- repeat above concern in the readme
- update all examples to use temurin
- stop updating openjdk images, remove them from the build

**Comment by eed3si9n** [comment]
Now that this image is under new management/`sbtscala`, I think there's some degree of design freedom we earned under the new name. I personally see Ubuntu and Debian both as distribution of `deb`-based distro.

**Comment by francisdb** [comment]
Readme was update in 4d959120f79c14fecc87407032cf9bb26c2e148a
Will for now namespace the openjdk images as `openjdk-*` so that users don't think these are the default images.
