### ISSUE TITLE
How do we get rid of the scheduled unstable builds?

### ISSUE THREAD

**Issue by francisdb** [sbt/docker-sbt#217]
**Current situation**

Every night we trigger a build
First we check the latest sbt version
Then we build the matrix of images

**Issues**

- This is a waste of cpu / space / bandwidth
- This causes unstable tags where the underlying image might change over night
- Combined this might causes our users to pull new images every time
- It's unclear from what repo state images were built

I was thinking to have the latest sbt version committed and a tag created (could be auto updated by some github action) and disabling the nightly builds.

Any other proposals are welcome.

**Comment by Carbrex** [comment]
https://github.com/scala-steward-org/scala-steward/blob/e1ed4e290c3a89d3a0a177fbd4b15613c5c941fc/docs/repo-specific-configuration.md
I think this might help?

**Comment by francisdb** [comment]
While this is great for sbt projects I fear this won't help here. Anyway I'm going to close this issue as the current solution works fine and it looks like the upstream images are also being updated frequently without having jdk updates.
