### ISSUE TITLE
Include exact eclipse-temurin version in final tag

### ISSUE THREAD

**Issue by jtjeferreira** [sbt/docker-sbt#232]
For example, instead of `eclipse-temurin-11.0.16_1.8.0_2.13.10` [link](https://hub.docker.com/r/sbtscala/scala-sbt/tags?page=1&name=eclipse-temurin-11.0.16_1.8.0_2.13.10) the tag should be `eclipse-temurin-11.0.16.1_1_1.8.0_2.13.10` because thats the version used in the eclipse-temurin docker image [link](https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=11.0.16.1_1). I mean it should be `11.0.16.1_1` and not just `11.0.16`.

This would be useful to make it easier to use both images in a single Dockerfile...

**Comment by francisdb** [comment]
Should be fixed, thanks for reporting this @jtjeferreira

**Comment by jtjeferreira** [comment]
@francisdb thanks for the fast response. However I see some errors in [github actions](https://github.com/sbt/docker-sbt/actions/runs/3734857794/jobs/6337593888)

**Comment by francisdb** [comment]
these builds tend to be a bit flaky, third time's a charm

**Comment by francisdb** [comment]
They went through this time.
