### ISSUE TITLE
Publish focal based images

### ISSUE THREAD

**Issue by jrduncans** [sbt/docker-sbt#235]
eclipse-temurin publishes both `focal` and `jammy` images for the Ubuntu releases they are based upon. 

This creates problems for some uses: https://github.com/keeganwitt/docker-gradle/wiki/Troubleshooting:-JAVA_HOME-is-set-to-an-invalid-directory

Following what `docker-gradle` project is doing, it would be very helpful for `docker-sbt` to publish `focal` based images.

**Comment by francisdb** [comment]
do we not have enough with specific `jammy` images only?

**Comment by jrduncans** [comment]
`jammy` is incompatible with Docker host versions commonly in use, at least in my environment (details in that linked Wiki page). I don't know how long that will be true, but at the moment not having a `focal` image is getting in the way of me being able to use `docker-sbt` images.

**Comment by francisdb** [comment]
@jrduncans can you check if the new images are working for your use case?

https://hub.docker.com/r/sbtscala/scala-sbt/tags?page=1&name=eclipse-temurin-focal

**Comment by jrduncans** [comment]
Yes, I was able to run a build successfully with `eclipse-temurin-focal-17.0.5_8_1.8.2_2.13.10`!
