### ISSUE TITLE
Publish Ubuntu Noble Numbat based images

### ISSUE THREAD

**Issue by fiaxh** [sbt/docker-sbt#309]
Currently, the most recent base image used by docker-sbt is based on Ubuntu Jammy Jellyfish (22.04). Ubuntu 22.04 is already a bit older, and consequently the packages shipped with it are a somewhat outdated. This is a problem for scala applications that depend on more recent package versions.

`eclipse-temurin` also publishes images based on Ubuntu Noble Numbat (24.04). It would be great if docker-sbt could also publish Noble Numbat-based images.

**Comment by francisdb** [comment]
Thanks for pointing this out, setting up a PR to tackle this.
