### ISSUE TITLE
consider adding docker?

### ISSUE THREAD

**Issue by fommil** [sbt/docker-sbt#311]
Hi, thanks for your efforts here, they are really appreciated. I used to maintain these sorts of things years ago, it has always been a huge gap in the whole community that these things didn't exist.

A lot of builds use `sbt-docker` to spin up integration tests, or `sbt-native-packager` to produce docker outputs. I would go so far as to say that it's standard practice nowadays to do this for anything except a published library jar.

Would you be open to adding the `docker` binary (and possibly even `docker-compose`, although that is perhaps more niche) to your base images to accommodate that very common usecase?

It's no big thing if you say no, your images already provide a great base for teams to add their build deps onto.

**Comment by fommil** [comment]
bah, please ignore, I posted this to completely the wrong repo 🤦🏻

**Comment by eed3si9n** [comment]
Yo dawg I heard you like cgroups? 

what are the potential pros and cons? would people be able to run it without the privilege mode of they don't need to build a docker image?

**Comment by francisdb** [comment]
Personally not a fan of adding more stuff.
Creating your own image that starts with this one and adds the docker layer should not be that hard?

**Comment by fommil** [comment]
I don't believe there would be any additional requirement for people using it as-is. Privileged mode or passing a socket through would only be necessary when spawning a new container.
